### ISSUE TITLE
Ignore case on the `file path` filter.

### ISSUE THREAD

**Issue by kppullin** [Kareo/Hound#4]
Hound does not honor the `ignore case` checkbox when filtering by `file path`.  It would be nice to do this or maybe ignore case all the time... case sensitive paths are generally silly.

**Comment by kppullin** [comment]
As a workaround, the ignore case regex flag does work.  Ex: `(?i)XML`

**Comment by gwindes** [comment]
Is this still an issue? I don't happen to use the path field much
